name: Test, Build and Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install dependencies
        run: npm ci
      - name: build project
        run: npm run build
      # using this action to upload the built artifacts:
      # https://github.com/actions/upload-artifact
      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist-files
          path: |
            dist/
            package.json
            package-lock.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # using this action to download the built artifacts:
      # https://github.com/actions/download-artifact
      - name: get built artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files
      - name: output contents
        run: ls -lah
      - name: deploy
        run: echo "Deploying..."
        